name: Bug Report
description: Report a bug in the LDF VS Code Extension
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.

        **Tip:** Include Extension Host logs from Help > Toggle Developer Tools > Console

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open VS Code
        2. Use command `LDF: Create New Spec`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: Found in the Extensions panel
      placeholder: "1.1.1"
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: From Help > About
      placeholder: "1.85.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    id: ldf-version
    attributes:
      label: LDF CLI Version (if applicable)
      description: Output of `ldf --version`
      placeholder: "1.1.2"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Extension Host Logs
      description: From Developer Tools Console (filter for "ldf" related errors)
      render: shell
    validations:
      required: false

  - type: textarea
    id: settings
    attributes:
      label: Relevant VS Code Settings
      description: Any LDF-related settings from your settings.json
      render: json
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I agree to follow the project's Code of Conduct
          required: true
