name: Feature Request
description: Suggest a new feature or enhancement for the LDF VS Code Extension
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see
      placeholder: I would like the extension to...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the extension does this relate to?
      options:
        - Spec Tree View
        - Guardrail Coverage Panel
        - Task Progress View
        - Commands
        - Code Snippets
        - Status Bar
        - Settings/Configuration
        - Workspace Support
        - Other
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I agree to follow the project's Code of Conduct
          required: true
