name: Question / Help
description: Ask a question or get help with the LDF VS Code Extension
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Need help with the LDF VS Code Extension? We're happy to assist!

        **Tip:** For general questions and discussions, consider using [GitHub Discussions](https://github.com/LLMdotInfo/ldf-vscode/discussions) instead.

        **Note:** For issues with the LDF CLI tool itself (not the extension), please use the [LDF CLI repository](https://github.com/LLMdotInfo/ldf/issues).

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
      placeholder: How do I...
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What steps have you already taken to find an answer?
      placeholder: |
        - Checked the README
        - Looked at extension settings
        - Searched existing issues
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add any relevant screenshots or configuration
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Extension Version
      description: Found in the Extensions panel
      placeholder: "1.1.1"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I agree to follow the project's Code of Conduct
          required: true
